version: '3'
services:
  postgres:
    image: postgres
    container_name: postgres
    restart: always
    environment:
    # default user is "postgres"
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    networks: 
      - fullstack-tool-network

  # when connecting to postgres use as "hostname/adress" - "postgres"
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin4
    links:
      - postgres
    depends_on:
      - postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    networks:
      - fullstack-tool-network

  # challenge-platform-backend:
  #   image: challenge-platform-backend:latest
  #   container_name: challenge-platform
  #   ports:
  #     - "8080:8080"
  #   restart: unless-stopped
  #   depends_on:
  #     - postgres
  #   links:
  #     - postgres
  #   networks:
  #     - fullstack-tool-network

  # challenge-platform-frontend:

networks:
  fullstack-tool-network:
    driver: bridge
  